/*
 * This source file was generated by the Gradle 'init' task
 */
package com.restfulbooker.api;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertEquals(true, true);
    }
}
